Upgrade/package version
masalabs/MASA.Framework.Admin pull request #15
Opened 2023-04-28 10:57 UTC by MapleWithoutWords

2023-05-04 08:19 UTC, doddgu commented
@capdiem @zhenlei520 PTAL

2023-05-05 03:51 UTC, capdiem requested changes

2023-05-05 03:51 UTC, capdiem commented on src/Web/Masa.Framework.Admin.Web/Pages/App/Invoice/Add.razor
> +            <MSwitch Value=false Class="mt-n3" Color="#7367f0" Label="Payment Stub"></MSwitch>
只是演示的代码吗？`Value=true/false`说实话没什么用，都改成 `TValue="bool"`。

2023-05-05 03:51 UTC, capdiem commented on src/Web/Masa.Framework.Admin.Web/Pages/App/Todo/TodoDetail.razor.cs
> +            _mForm.Reset();
ResetValidation

2023-05-05 03:51 UTC, capdiem commented on src/Web/Masa.Framework.Admin.Web/Pages/App/User/Edit.razor
> +                            <MCheckbox Label="Phone" HideDetails="@("auto")" Color="primary" Class="ml-2" Value="false"></MCheckbox>
不是加`Value=false`，是加`TValue="bool"`

2023-05-05 03:51 UTC, capdiem commented on src/Web/Masa.Framework.Admin.Web/Pages/Authentication/Components/Register.razor
> +        <MCheckbox Value=false Class="mt-0 pt-0" Color="#7367f0" Label="I agree to privacy policy & terms"></MCheckbox>
`TValue=bool`

2023-05-05 03:51 UTC, capdiem commented on src/Web/Masa.Framework.Admin.Web/Pages/Others/AccountSettings/AccountSettings.razor
> +                <MSwitch Value="false" Label="Weekly blog digest"></MSwitch>
`TValue=bool`

2023-05-09 03:15 UTC, zhenlei520 requested changes

2023-05-09 03:15 UTC, zhenlei520 commented on sdks/MASA.Framework.Sdks.Authentication/MASA.Framework.Sdks.Authentication.csproj
> +    <PackageReference Include="Masa.Contrib.Service.Caller.HttpClient" Version="$(MasaUtilsPackageVersion)" />
Version = "$(MasaContribPackageVersion)"

2023-05-09 03:15 UTC, zhenlei520 commented on sdks/MASA.Framework.Sdks.Authentication/_Imports.cs
> +global using Masa.Contrib.Service.Caller.HttpClient;
global using sort

2023-05-09 03:15 UTC, zhenlei520 commented on Directory.Build.props
> +    <MasaUtilsPackageVersion>1.0.0-rc.1</MasaUtilsPackageVersion>
Utils and Contrib share the same version, which can be controlled by a parameter, and subsequent versions also use the same parameter to make it easier to understand

2023-05-09 03:15 UTC, zhenlei520 commented on src/Services/Masa.Framework.Admin.Service.Authentication/Masa.Framework.Admin.Service.Authentication.csproj
> +      <PackageReference Include="Masa.Contrib.Caching.MultilevelCache" Version="$(MasaUtilsPackageVersion)" />
The same is true below

2023-05-09 03:15 UTC, zhenlei520 commented on src/Services/Masa.Framework.Admin.Service.Authentication/Program.cs
> +using Masa.BuildingBlocks.Dispatcher.IntegrationEvents;
use global using

2023-05-09 03:15 UTC, zhenlei520 commented on src/Services/Masa.Framework.Admin.Service.LogStatistics/_Imports.cs
> +global using Masa.BuildingBlocks.Dispatcher.IntegrationEvents;
use global using

2023-05-09 03:15 UTC, zhenlei520 commented on src/Services/Masa.Framework.Admin.Service.User/_Imports.cs
> +global using Masa.BuildingBlocks.Dispatcher.IntegrationEvents;
use global using

2023-05-09 03:15 UTC, zhenlei520 commented on src/Web/Masa.Framework.Admin.Web/_Imports.cs
> +global using Masa.Contrib.Service.Caller;
use global using

2023-05-09 03:17 UTC, zhenlei520 commented on sdks/MASA.Framework.Sdks.Authentication/MASA.Framework.Sdks.Authentication.csproj
> +    <PackageReference Include="Masa.Contrib.Service.Caller.HttpClient" Version="$(MasaUtilsPackageVersion)" />
The same is true below, It is recommended that Masa Framework use the same parameter to control the version

2023-05-09 03:19 UTC, zhenlei520 commented on src/Services/Masa.Framework.Admin.Service.Authentication/Program.cs
> +builder.Services.AddDistributedCache(options=>options.UseStackExchangeRedisCache());
Multi-level caching is required here

2023-05-09 14:53 UTC, capdiem requested changes

2023-05-09 14:53 UTC, capdiem commented on src/Web/Masa.Framework.Admin.Web/Program.cs
> -}).AddGlobalForServer();
Pro的配色不能删

2023-05-10 02:19 UTC, zhenlei520 approved these changes
LGTM @capdiem

2023-05-10 02:48 UTC, capdiem approved these changes
LGTM!

2023-05-10 02:48 UTC, capdiem approved these changes

2023-05-10 02:48 UTC, capdiem approved these changes

2023-05-10 02:52 UTC, MayueCif approved these changes

2023-05-10 02:52 UTC, merged